version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
      
    working_directory: /go/src/github.com/dtylman/connan
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run:
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install -y nodejs
            cd ~ ; npm install nw-builder --save-dev            
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run:
          command: |
            ~/node_modules/nw-builder/bin/nwbuild -p win64,osx64,linux64 /go/src/github.com/dtylman/connan/      
            GOOS=windows go build -o ~/build/connan/win64/connancmd.exe
            GOOS=darwin go build -o ~/build/connan/osx64/connancmd
            go build o ~/build/connan/linux64/connancmd
            zip ~/connan_linux64.zip /home/circleci/build/connan/linux64/*
            zip ~/connan_win64.zip /home/circleci/build/connan/win64/*
            zip ~/connan_osx64.zip /home/circleci/build/connan/osx64/*
      - store_artifacts:
          path: ~/connan_win64.zip
      - store_artifacts:
          path: ~/connan_osx64.zip        
      - store_artifacts:
          path: ~/connan_linux64.zip          
